# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Free words
subtitle: When you feel something right, share it
email: benemanuel at geulah dot org dot il
description: >- # this means to ignore newlines until "baseurl:"
  Avi (Wollman) Benemanuel's Homepage
baseurl: "/website" # the subpath of your site, e.g. /blog
url: "https://benemanuel.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: aviwollman
github_username:  benemanuel
facebook_username: son.of.emanuel
instagram_username: avrahambenemanuel
linkedin_username: avibenemanuel
youtube_username: AvrahamBenEmanuel

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
permalink: :title


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%d/%m/%Y"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
google_analytics: G-NVGSYBHJFV
show_excerpts: true
