version: "3.9"

services:
  jekyll:
    image: bretfisher/jekyll-serve
    container_name: blog-builder
    volumes:
      - .:/site
    command: jekyll build      # Build once
    # Optional: remove after build
    restart: "no"

  web:
    image: nginx:alpine
    container_name: blog-web-server
    ports:
      - "4007:80"              # host:container
    volumes:
      - ./_site:/usr/share/nginx/html:ro
    restart: always
