services:
  jekyll:
    image: jekyll/jekyll:4.3.2
    container_name: blog-web-server-builder
    hostname: blog-web-server-builder
    volumes:
      - .:/srv/jekyll
    command: >
      sh -c "bundle install && JEKYLL_ENV=production bundle exec jekyll build"

  web:
    image: nginx:alpine
    container_name: blog-web-server
    hostname: blog-web-server
    restart: always
    ports:
      - "4007:80"
    volumes:
      - ./_site:/usr/share/nginx/html:ro
